CREATE TABLE [eco].[APIMemberTasks](
	[ID] INT IDENTITY(1,1)	NOT NULL,
	[TaskID] INT			NOT NULL,
	[Review] NVARCHAR(250)  NULL,
	[Rate]	 SMALLINT		NULL,
	CONSTRAINT [PK_UserApplicationsTasks] PRIMARY KEY CLUSTERED ([ID] ASC)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) 

GO

ALTER TABLE [eco].[APIMemberTasks] ADD  CONSTRAINT [FK_Tasks] FOREIGN KEY([TaskID])
REFERENCES [eco].[Tasks] ([Id])
GO




